apiVersion: config.kwok.x-k8s.io/v1alpha1
kind: KwokctlConfiguration
metadata:
  creationTimestamp: null
  components:
 # - name: kube-apiserver
 #   Command:
 #   - kube-apiserver 
 #   Args:
 #   - --allow-privileged=true
 #   - --etcd-servers=http://kwok-demo-etcd:2379
 #   - --etcd-prefix=/registry
 #   - --bind-address=0.0.0.0
 #   - --secure-port=6443
 #   - --tls-cert-file=/etc/kubernetes/pki/admin.crt
 #   - --tls-private-key-file=/etc/kubernetes/pki/admin.key
 #   - --client-ca-file=/etc/kubernetes/pki/ca.crt
 #   - --service-account-key-file=/etc/kubernetes/pki/admin.key
 #   - --service-account-signing-key-file=/etc/kubernetes/pki/admin.key
 #   - --service-account-issuer=https://kubernetes.default.svc.cluster.local
 #   - --proxy-client-key-file=/etc/kubernetes/pki/admin.key
 #   - --proxy-client-cert-file=/etc/kubernetes/pki/admin.crt
 #   - --max-requests-inflight=4000
 #   - --max-mutating-requests-inflight=2000
 #   - --request-timeout=1m
 #   - --min-request-timeout=300
  #  ports:
  #  - port: 10259
  #    hostPort: 30259
  #    name: test
componentsPatches:
- name: kube-apiserver
  extraArgs:
  - key: max-requests-inflight
    value: "10000"
  - key: max-mutating-requests-inflight
    value: "5000"
  - key: request-timeout
    value: 300s
  - key: min-request-timeout
    value: "180"
- name: kube-scheduler
  extraArgs:
  - key: bind-address
    value: 0.0.0.0
    override: true
  - key: secure-port
    value: "10259"
    override: true
  - key: authentication-always-allow-paths
    value: /metrics
    override: true
options:
  bindAddress: 0.0.0.0
  cacheDir: /root/.kwok/cache
  components:
  - etcd
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kwok-controller
  dashboardImage: docker.io/kubernetesui/dashboard:v2.7.0
  dashboardMetricsScraperImage: docker.io/kubernetesui/metrics-scraper:v1.0.9
  dashboardMetricsScraperVersion: v1.0.9
  dashboardVersion: v2.7.0
  disableKubeControllerManager: false
  disableKubeScheduler: false
  disableQPSLimits: false
  enableMetricsServer: false
  etcdBinary: https://github.com/etcd-io/etcd/releases/download/v3.5.21/etcd-v3.5.21-linux-amd64.tar.gz#etcd
  etcdImage: registry.k8s.io/etcd:3.5.21-0
  etcdPrefix: /registry
  etcdQuotaBackendSize: 8Gi
  etcdVersion: 3.5.21-0
  etcdctlBinary: https://github.com/etcd-io/etcd/releases/download/v3.5.21/etcd-v3.5.21-linux-amd64.tar.gz#etcdctl
  heartbeatFactor: 5
  jaegerBinary: https://github.com/jaegertracing/jaeger/releases/download/v1.69.0/jaeger-1.69.0-linux-amd64.tar.gz#jaeger-all-in-one
  jaegerImage: docker.io/jaegertracing/all-in-one:1.69.0
  jaegerVersion: v1.69.0
  kectlBinary: https://github.com/kwok-ci/kectl/releases/download/v0.0.8/kectl_linux_amd64
  kectlVersion: 0.0.8
  kindBinary: https://github.com/kubernetes-sigs/kind/releases/download/v0.27.0/kind-linux-amd64
  kindNodeImage: docker.io/kindest/node:v1.32.3
  kindVersion: v0.27.0
  kubeAdmission: true
  kubeApiserverBinary: https://dl.k8s.io/release/v1.32.3/bin/linux/amd64/kube-apiserver
  kubeApiserverImage: registry.k8s.io/kube-apiserver:v1.32.3
  kubeAuthorization: true
  kubeControllerManagerBinary: https://dl.k8s.io/release/v1.32.3/bin/linux/amd64/kube-controller-manager
  kubeControllerManagerImage: registry.k8s.io/kube-controller-manager:v1.32.3
  kubeControllerManagerNodeMonitorGracePeriodMilliseconds: 40000
  kubeControllerManagerNodeMonitorPeriodMilliseconds: 5000
  kubeSchedulerBinary: https://dl.k8s.io/release/v1.32.3/bin/linux/amd64/kube-scheduler
  kubeSchedulerImage: registry.k8s.io/kube-scheduler:v1.32.3
  kubeSchedulerConfig: ./none-score-kube-schduler-config.yaml
  kubeVersion: v1.32.3
  kubectlBinary: https://dl.k8s.io/release/v1.32.3/bin/linux/amd64/kubectl
  kubectlImage: registry.k8s.io/kubectl:v1.32.3
  kwokControllerBinary: https://github.com/kubernetes-sigs/kwok/releases/download/v0.7.0/kwok-linux-amd64
  kwokControllerImage: registry.k8s.io/kwok/kwok:v0.7.0
  kwokVersion: v0.7.0
  metricsServerBinary: https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.7.2/metrics-server-linux-amd64
  metricsServerImage: registry.k8s.io/metrics-server/metrics-server:v0.7.2
  metricsServerVersion: v0.7.2
  nodeLeaseDurationSeconds: 40
  nodeStatusUpdateFrequencyMilliseconds: 10000
  prometheusBinary: https://github.com/prometheus/prometheus/releases/download/v3.3.1/prometheus-3.3.1.linux-amd64.tar.gz#prometheus
  prometheusImage: docker.io/prom/prometheus:v3.3.1
  prometheusVersion: v3.3.1
  quietPull: false
  runtimes:
  - docker
  - podman
  - nerdctl
  - binary
  securePort: true
status: {}
